#!/bin/bash

if [ $(whoami) != 'root' ]; then
    echo "You Are Not Root!"
    exit 1
elif [ -z $(which go) ]; then
    echo "go is not installed"
    exit 1
elif [ -z $(which snap) ]; then
    echo "snap is not installed"
    exit 1
fi

if [ -z $RYN_ADMIN_PASSWORD ]; then
    echo "Please Add Your Admin Password to RYN_ADMIN_PASSWORD (Should Be 16 Characters)"
fi

chmod +x systemUtils/mngusers
mv systemUtils/mngusers /usr/bin/mngusers
mv systemUtils/killabuse.service /etc/systemd/system
mkdir /usr/share/rynPanel
mv * /usr/share/rynPanel
cd /usr/share/rynPanel
go build .
mv rynpanel /usr/bin
