#!/bin/sh

if [ -z $RYNPORT ]; then
    RYNPORT=22
fi

if [ $(whoami) != 'root' ]; then
    echo "this Script Should Only Work as root"
    exit 1
fi

list_users() {
    cat /etc/passwd | grep -e '10[0-9][0-9]' | cut -d ':' -f1 | while read line; do
        echo "$line\t$(chage -l $line | awk '/Account exp/ {print $4,$5,$6}')" | sed 's/,//'
    done
}

if [ -z $1 ]; then
    echo "Usage: mngusers [command]"
    echo "Commands:"
    echo "\tCreate New User -> add [user] [password] [day]"
    echo "\tDelete User -> del [user]"
    echo "\tExtending Expiration Date -> extendExp [days] [user]"
    echo "\tLock User -> lock [user]"
    echo "\tUnlock User-> unlock [user]"
    echo "\tChange Password -> passwd [password] [user]"
    echo "\tList Users -> list"

elif [ $1 = 'extendExp' ]; then

    usermod -e $(date --date="$2" +"%F") $3
    echo "Changed Exiration Date of $3 $2"

elif [ $1 = 'lock' ]; then

    loginctl terminate-user $3
    usermod -L $2
    echo "User $2 Locked"

elif [ $1 = 'unlock' ]; then

    loginctl terminate-user $3
    usermod -U $2
    echo "User $2 Unlocked"

elif [ $1 = 'passwd' ]; then

    loginctl terminate-user $3
    usermod -p $(echo $2 | openssl passwd -1 -stdin) $3
    echo "Password Changed => $3 -> $2"

elif [ $1 = 'list' ]; then

    list_users

elif [ $1 = 'add' ]; then

    useradd -M -s /usr/sbin/nologin -e $(date --date="+${4} day" +"%F") -p $(echo $3 | openssl passwd -1 -stdin) $2
    echo "Host: $(cat /etc/hostname)"
    echo "Port: $RYNPORT"
    echo "Username: $2"
    echo "Password: $3"
    echo "Expire: $(date --date="+${4} day" +"%F")"

elif [ $1 = 'del' ]; then

    loginctl terminate-user $2
    deluser $2
    echo "User $2 Has Been Deleted"

elif [ $1 = 'test' ]; then
    echo $# $@
fi
